name: Tag Docker Image Based on CHANGELOG.md

on:
  push:
    branches:
      - master

jobs:
  tag-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Extract version from CHANGELOG.md
        id: extract_version
        run: |
          VERSION=$(grep -oP '## \[\K[^\]]+' CHANGELOG.md | head -n 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log extracted version
        run: |
          echo "Extracted version: ${{ env.VERSION }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t webapp:${{ env.VERSION }} .

      - name: Tag and push Docker image
        run: |
          docker tag webapp:${{ env.VERSION }} juliopedrosa/webapp:${{ env.VERSION }}
          docker push juliopedrosa/webapp:${{ env.VERSION }}